scr/auth.py
import sqlalchemy.exc
import datetime
import bcrypt
import yagmail
from flask import Blueprint, request, redirect, url_for, flash
from .models import Usuario, db, TangramCoin, SenhaReset, PerguntasQuiz, PerguntasRespondidas, PerguntasDesempenho
from flask_login import login_required, login_user, logout_user, current_user
from .help_functions import gerar_key, email_user, email_passw, \
    url_do_site, atualizar_perfil_func, eh_menor_que_essa_quantidade_de_caracters, atualizar_pergunta_func


auth = Blueprint('auth', __name__)


@auth.route('/cadastrar', methods=['POST',])
def cadastrar():
    if request.method == "POST":
        nome = request.form.get('nome')
        email = request.form.get('email')
        senha1 = request.form.get('senha')
        senha2 = request.form.get('senha2')

        senha_sao_iguais = senha1 == senha2

        if not senha_sao_iguais:
            flash('Senhas não são iguais', category="error")
            return redirect(url_for('views.cadastro'))
        elif len(senha1) < 3:
            flash('Senha muito curta', category="error")
            return redirect(url_for('views.cadastro'))
        else:
            try:
                salt = bcrypt.gensalt()
                senha_cripto = bcrypt.hashpw(senha1.encode('utf-8'), salt)
                if current_user.is_authenticated:
                    # cria professor se for admin
                    if current_user.has_role == 1:
                        novo_professor = Usuario(nome=nome, email=email, senha=senha_cripto, role=2)
                        db.session.add(novo_professor)
                        db.session.commit()
                        flash('Professor cadastrado com sucesso!', category="success")
                else:
                    # aluno default
                    novo_usuario = Usuario(nome=nome, email=email, senha=senha_cripto, role=3)
                    db.session.add(novo_usuario)
                    db.session.commit()
                    flash('Conta criada com sucesso!', category="success")
            except sqlalchemy.exc.IntegrityError:
                flash('E-mail já registrado', category='error')
                return redirect(url_for('views.cadastro'))
            return redirect(url_for('views.home'))


@auth.route('/login-confirm', methods=['POST', ])
def login_confirm():
    if request.method == "POST":
        email_net = request.form.get('email')
        senha_net = request.form.get('password')

        usuario = Usuario.query.filter_by(email=email_net).first()

        if usuario:
            if bcrypt.checkpw(senha_net.encode('utf-8'), usuario.senha):
                flash('Logado com sucesso!', category='sucess')
                login_user(usuario, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Senha digitada inválida!', category='error')
                return redirect(url_for('views.login'))
        else:
            # verificação "atoa" para evitar > "ACCOUNT ENUMERATION VIA TIMING ATTACKS"
            senha_hash = "$2a$12$zlU2BApnYUfTsxOUgOQ8wuk.cFsFqFq2g.d/DC3X2N74TOa7yF27e"
            if bcrypt.checkpw(senha_net.encode('utf-8'), senha_hash.encode('utf-8')):
                pass
            flash('Usuário não encontrado!', category='error')
            return redirect(url_for('views.login'))


@auth.route('/logout')
@login_required
def logout():
    flash('Deslogado com sucesso!', category='sucess')
    logout_user()
    return redirect(url_for('views.home'))


@auth.route('/resetar_senha', methods=['POST',])
def resetar_senha():
    email = request.form.get('email')
    usuario = Usuario.query.filter_by(email=email).first()
    if usuario:
        ja_tem_senha_reset = SenhaReset.query.filter_by(user_id = usuario.id).first()
        if ja_tem_senha_reset:
            if ja_tem_senha_reset.has_activated is False:
                ja_tem_senha_reset.datetime = datetime.datetime.now()
                chave = ja_tem_senha_reset.reset_key
            else:
                chave = gerar_key()
                ja_tem_senha_reset.reset_key = chave
                ja_tem_senha_reset.datetime = datetime.datetime.now()
                ja_tem_senha_reset.has_activated = False
        else:
            chave = gerar_key()
            user_reset = SenhaReset(reset_key=chave, user_id=usuario.id)
            db.session.add(user_reset)
        db.session.commit()
        yag = yagmail.SMTP(email_user(), email_passw())
        url_site = url_do_site()
        contents = ['Por favor acesse essa url para trocar a senha:',
                    url_site + url_for("views.nova_senha_get", id=(str(chave)))]
        email_cadastrado = request.form.get("email")
        try:
            yag.send(email_cadastrado, 'Reset your password', contents)
            flash(usuario.nome + ", Confira seu Email para trocar de senha, verifique o spam também! Link expira em 45 mins!", category='success')
            return redirect(url_for("views.home"))
        except:
            flash(usuario.nome + ", Ocorreu algum erro ao enviar o Email, verifique se o seu Email é válido!", category='error')
            return redirect(url_for("views.home"))
    else:
        flash("Email não encontrado!", category='error')
        return redirect(url_for('views.reset_senha'))


@auth.route("/troca-senha/<id>", methods=['POST',])
def nova_senha_post(id):
    if request.form["senha1"] != request.form["senha2"]:
        flash("As senhas estão diferentes", category="error")
        return redirect(url_for("views.nova_senha_get", id=id))
    if len(request.form["senha1"]) < 3:
        flash("Senha muito curta!", category="error")
        return redirect(url_for("views.nova_senha_get", id=id))
    usuario_reset = SenhaReset.query.filter_by(reset_key=id).one()
    try:
        salt = bcrypt.gensalt()
        senha1 = request.form.get("senha1")
        senha_cripto = bcrypt.hashpw(senha1.encode('utf-8'), salt)
        Usuario.query.filter_by(id=usuario_reset.user_id).update({'senha': senha_cripto})
        db.session.commit()
    except sqlalchemy.exc.IntegrityError:
        flash("Aconteceu algum erro!", category="error")
        db.session.rollback()
        return redirect(url_for("views.home"))
    usuario_reset.has_activated = True
    db.session.commit()
    flash("Senha trocado com sucesso!", category="success")
    return redirect(url_for("views.home"))


@auth.route('/atualizar-perfil', methods=['POST',])
def atualizar_perfil():
    if request.form.get('atualiza') == 'Atualizar Perfil':
        nome = request.form.get('nome')
        email = request.form.get('email')
        senha = request.form.get('senha')
        try:
            if atualizar_perfil_func(nome, email, senha):
                db.session.commit()
                flash("Perfil atualizado com sucesso!", category="success")
            else:
                flash("Nada foi atualizado", category="warming")
        except sqlalchemy.exc.IntegrityError:
            flash("Email já em uso", category="error")
            db.session.rollback()
        return redirect(url_for('views.perfil'))
    if request.form.get('deleta') == 'Deletar a conta':
        try:
            user = db.session.query(Usuario).filter(Usuario.id == current_user.id).first()
            db.session.delete(user)
            db.session.commit()
            flash("Conta deletado com sucesso!", category="success")
            return redirect(url_for('views.login'))
        except sqlalchemy.exc.IntegrityError:
            flash("Aconteceu algum erro", category="error")
            db.session.rollback()
        return redirect(url_for('views.perfil'))


@auth.route('/nova_pergunta_create', methods=['POST',])
def nova_pergunta():
    titulo = request.form.get('titulo')
    pergunta = request.form.get('pergunta')
    resposta_1 = request.form.get('resposta_1')
    resposta_2 = request.form.get('resposta_2')
    resposta_3 = request.form.get('resposta_3')
    resposta_4 = request.form.get('resposta_4')
    resposta_certa = request.form.get('resposta_certa')
    questao_dificuldade = request.form.get('questao_dificuldade')
    if not eh_menor_que_essa_quantidade_de_caracters(titulo, 79):
        flash("Seu título é muito comprido, por favor o diminua", category='warming')
        return redirect(url_for('views.nova_pergunta'))
    else:
        if resposta_certa == 'Selecione a resposta correta':
            flash("Você não selecionou a resposta para a pergunta!", category='warming')
            return redirect(url_for('views.nova_pergunta'))
        else:

            try:
                novo_pergunta = PerguntasQuiz(professor_id=current_user.id, pergunta_titulo=titulo,
                                              pergunta=pergunta, resp_1=resposta_1,
                                              resp_2=resposta_2, resp_3=resposta_3,
                                              resp_4=resposta_4, resposta_certa=int(resposta_certa),
                                              questao_dificuldade=questao_dificuldade)

                db.session.add(novo_pergunta)
                db.session.commit()
                flash("Pergunta Registrada com sucesso!", category='success')
            except:
                flash("Ops, ocorreu algum erro!", category="error")
            return redirect(url_for('views.home'))


@auth.route('/resposta_verificacao', methods=['POST',])
def verificar_resposta():
    resposta_escolhida = int(request.form.get('resposta'))
    id_pergunta = request.form.get('pergunta_id')
    pergunta = PerguntasQuiz.query.filter_by(id=id_pergunta).first()
    acertou = resposta_escolhida == pergunta.resposta_certa
    if acertou:
        flash("Voceu acertou! Parabéns!", category="success")
        pergunta_respondida = PerguntasRespondidas(aluno_id=current_user.id, pergunta_id=id_pergunta)
        carteira = TangramCoin.query.filter_by(player_id=current_user.id).first()

scr/templates/cadastro.html
{% extends "template.html" %}
{% block title %} Cadastro {% endblock %}
{% block conteudo %}
    <div class="login-root">
      <div
        class="box-root flex-flex flex-direction--column"
        style="min-height: 100vh; flex-grow: 1"
      >
      <div class="loginbackground box-background--white padding-top--64">
        <div class="loginbackground-gridContainer">
          <div
            class="box-root flex-flex"
            style="grid-area: top / start / 8 / end"
          >
            <div
              class="box-root"
              style="
                background-image: linear-gradient(
                  white 0%,
                  rgb(247, 250, 252) 33%
                );
                flex-grow: 1;
              "
            ></div>
          </div>
            <div
              class="box-root flex-flex"
              style="grid-area: 4 / 2 / auto / 5"
            >
              <div
                class="box-root box-divider--light-all-2 animationLeftRight tans3s"
                style="flex-grow: 1"
              ></div>
            </div>
            <div
              class="box-root flex-flex"
              style="grid-area: 6 / start / auto / 2"
            >
              <div
                class="box-root box-background--blue800"
                style="flex-grow: 1"
              ></div>
            </div>
            <div
              class="box-root flex-flex"
              style="grid-area: 7 / start / auto / 4"
            >
              <div
                class="box-root box-background--blue animationLeftRight"
                style="flex-grow: 1"
              ></div>
            </div>
            <div
              class="box-root flex-flex"
              style="grid-area: 8 / 4 / auto / 6"
            >
              <div
                class="box-root box-background--gray100 animationLeftRight tans3s"
                style="flex-grow: 1"
              ></div>
            </div>
            <div
              class="box-root flex-flex"
              style="grid-area: 2 / 15 / auto / end"
            >
              <div
                class="box-root box-background--cyan200 animationRightLeft tans4s"
                style="flex-grow: 1"
              ></div>
            </div>
            <div
              class="box-root flex-flex"
              style="grid-area: 3 / 14 / auto / end"
            >
              <div
                class="box-root box-background--blue animationRightLeft"
                style="flex-grow: 1"
              ></div>
            </div>
            <div
              class="box-root flex-flex"
              style="grid-area: 4 / 17 / auto / 20"
            >
              <div
                class="box-root box-background--gray100 animationRightLeft tans4s"
                style="flex-grow: 1"
              ></div>
            </div>
            <div
              class="box-root flex-flex"
              style="grid-area: 5 / 14 / auto / 17"
            >
              <div
                class="box-root box-divider--light-all-2 animationRightLeft tans3s"
                style="flex-grow: 1"
              ></div>
            </div>
          </div>
        </div>
        <div
          class="box-root padding-top--24 flex-flex flex-direction--column"
          style="flex-grow: 1; z-index: 9"
        >
          <div
            class="box-root padding-top--48 padding-bottom--24 flex-flex flex-justifyContent--center"
          >
          <span
          ><img
            src="../static/img/tg-logo.png"
            alt="logoTamgram"
            width="150px"
            height="150px"

             /></span
      ></a>
            <h1>
              <a

                rel="dofollow"
                style="
                  color: #299bf3;
                  font-family: 'Poppins', sans-serif;
                  font-weight: bold;
                "
                >Tamgram Bank

            </h1>
          </div>
          <div class="formbg-outer">
            <div class="formbg">
              <div class="formbg-inner padding-horizontal--48">
                <div> {% include 'message.html' %} </div>
                <span class="padding-bottom--15">Preencha abaixo!!!🤓</span>
                <form id="stripe-login" action="{{ url_for('auth.cadastrar') }}" method="POST">
                  <div class="field padding-bottom--24">
                    <label for="nome">Nome</label>
                    <input type="text" name="nome" required/>
                  </div>
                  <div class="field padding-bottom--24">
                    <label for="email">Email</label>
                    <input type="email" name="email" required/>
                  </div>
                  <div class="field padding-bottom--24">
                    <div class="grid--50-50">
                      <label  for="password">Senha</label>

                    </div>
                    <input name="senha" type="password" required/>
                  </div>
                    <div class="grid--50-50">
                      <label for="password2">Confirme a senha</label>

                    </div>
                    <input  name="senha2" type="password" required />
                  </div>
                  <div
                    class="field field-checkbox padding-bottom--24 flex-flex align-center"
                  >
                    <label class="description" for="checkbox">
                      <input   type="checkbox" name="checkbox" /> Aprenda
                      matemática financeira de uma maneira divertida!!!
                    </label>
                  </div>





                  <div style="padding-bottom: 20px;" class="field">
                    <a class="ssolink" href="#">Quem Poupa ganha😜</a>
                  </div>
                  <!-- <button class="field padding-bottom--24" style="background-color: #299bf3" type="submit" class="btn btn-primary">Cadastrar</button> -->
                  <div class="field padding-bottom--24 btnCadastro">
                    <input class="btnCadastro"
                      style="background-color: #299bf3;width: 50%;align-items: center;margin-left: 25%;"
                      type="submit"
                      name="submit"
                      value="cadastrar"
                    />
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

scr/templates/criar_perguntas.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
            rel="stylesheet"
            href="{{ url_for('static', filename='style.css') }}"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>Crie sua pergunta</title>
</head>
<body>
    <header>{% include 'header.html' %}</header>
    <div>{% include 'message.html' %}</div>
    <main>
        <form role="form" method="POST" action="{{ url_for('auth.nova_pergunta') }}">
            <!-- titulo da pergunta -->
            <div class="row g-3 align-items-center">
              <div class="col-auto">
                <label for="inputTitulo" class="col-form-label">Título da pergunta</label>
              </div>
              <div class="col-auto">
                <input type="text" id="inputTitulo" class="form-control" aria-describedby="passwordHelpInline" name="titulo" required>
              </div>
              <div class="col-auto">
                <span id="passwordHelpInline" class="form-text">
                  Uma breve descrição da pergunta.
                </span>
              </div>
            </div>
            <!-- pergunta -->
            <div class="mb-3">
              <label for="TextareaPergunta" class="form-label">Pergunta: </label>
              <textarea class="form-control" id="TextareaPergunta" rows="3" name="pergunta" required></textarea>
            </div>
            <!-- respostas -->
            <div class="mb-3">
              <label for="TextareaResposta1" class="form-label">Resposta 1: </label>
              <textarea class="form-control" id="TextareaResposta1" rows="3" name="resposta_1" required></textarea>
            </div>
            <div class="mb-3">
              <label for="TextareaResposta2" class="form-label">Resposta 2: </label>
              <textarea class="form-control" id="TextareaResposta2" rows="3" name="resposta_2" required></textarea>
            </div>
            <div class="mb-3">
              <label for="TextareaResposta3" class="form-label">Resposta 3: </label>
              <textarea class="form-control" id="TextareaResposta3" rows="3" name="resposta_3" required></textarea>
            </div>
            <div class="mb-3">
              <label for="TextareaResposta4" class="form-label">Resposta 4: </label>
              <textarea class="form-control" id="TextareaResposta4" rows="3" name="resposta_4" required></textarea>
            </div>

            <!-- Seleção da pergunta certa -->
            <select class="form-select" aria-label="Default select example" name="resposta_certa">
              <option selected>Selecione a resposta correta</option>
              <option value="1">Primeira</option>
              <option value="2">Segunda</option>
              <option value="3">Terceira</option>
              <option value="4">Quarta</option>
            </select>

            <!-- Dificuldade da questão -->
            <br>
            <p>Dificuldade da questão:</p>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="questao_dificuldade" id="flexRadioDefault1" value="facil">
              <label class="form-check-label" for="flexRadioDefault1">
                Fácil
              </label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="questao_dificuldade" id="flexRadioDefault2" value="medio" checked>
              <label class="form-check-label" for="flexRadioDefault2">
                Médio
              </label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="questao_dificuldade" id="flexRadioDefault3" value="dificil">
              <label class="form-check-label" for="flexRadioDefault3">
                Difícil
              </label>
            </div>
            <br>
        <button type="submit" class="btn btn-primary">Confirmar</button>
        </form>
    </main>
    <footer>{% include 'footer.html' %}</footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
</body>
</html>

scr/templates/esqueceu_senha_solicitar.html
{% extends "template_dashboard.html" %}
{% block title %} Esqueceu Senha {% endblock %}
{% block conteudo %}
<div>{% include 'message.html' %}</div>
  </br>
  <h1>Troca de senha </h1>
  </br>
  <form role="form" method="POST" action="{{ url_for('auth.resetar_senha') }}">
    <div class="mb-3">
      <label for="Email" class="form-label">Endereço de Email</label>
      <input type="email" class="form-control" id="Email" aria-describedby="emailHelp" name="email" placeholder="Seu Email" required>
    </div>
  <button type="submit" class="btn btn-primary">Confirmar</button>
  </form>
{% endblock %}

scr/templates/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('views.home') }}">
                    <img src="../static/img/tg-logo.png" width="30" height="30" alt="Tangram Logo">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('views.home') }}">Home</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {% if user.has_role == 1 %}
                                    Admin, {{ user.nome }}
                                 {% elif user.has_role == 2 %}
                                    Prof, {{ user.nome }}
                                {% elif user.has_role == 3%}
                                    Estudante, {{ user.nome }}
                                {% endif %}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{{ url_for('views.perfil') }}" target="_self" rel="next">Perfil</a></li>
                                {% if user.has_role == 1 %}
                                <!-- Admin -->
                                    <li><a class="dropdown-item" href="#">Investir</a></li>
                                {% elif user.has_role == 2 %}
                                <!-- Professor -->
                                    <li><a class="dropdown-item" href="{{ url_for('views.perguntas_dash') }}" target="_self" rel="next">Suas Perguntas</a></li>
                                    <li><a class="dropdown-item" href="{{ url_for('views.nova_pergunta') }}" target="_self" rel="next">Criar Perguntas</a></li>
                                {% elif user.has_role == 3%}
                                <!-- Aluno -->
                                    <li><a class="dropdown-item" href="{{ url_for('views.responder_quiz') }}" target="_self" rel="next">Quiz</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Desconectar</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

scr/templates/login.html
{% extends "template.html" %}
{% block title %} Login {% endblock %}
{% block conteudo %}
  <div class="login-root">
    <div
      class="box-root flex-flex flex-direction--column"
      style="min-height: 100vh; flex-grow: 1"
    >
      <div class="loginbackground box-background--white padding-top--64">
        <div class="loginbackground-gridContainer">
          <div
            class="box-root flex-flex"
            style="grid-area: top / start / 8 / end"
          >
            <div
              class="box-root"
              style="
                background-image: linear-gradient(
                  white 0%,
                  rgb(247, 250, 252) 33%
                );
                flex-grow: 1;
              "
            ></div>
          </div>
          <div
            class="box-root flex-flex"
            style="grid-area: 4 / 2 / auto / 5"
          >
            <div
              class="box-root box-divider--light-all-2 animationLeftRight tans3s"
              style="flex-grow: 1"
            ></div>
          </div>
          <div
            class="box-root flex-flex"
            style="grid-area: 6 / start / auto / 2"
          >
            <div
              class="box-root box-background--blue800"
              style="flex-grow: 1"
            ></div>
          </div>
          <div
            class="box-root flex-flex"
            style="grid-area: 7 / start / auto / 4"
          >
            <div
              class="box-root box-background--blue animationLeftRight"
              style="flex-grow: 1"
            ></div>
          </div>
          <div
            class="box-root flex-flex"
            style="grid-area: 8 / 4 / auto / 6"
          >
            <div
              class="box-root box-background--gray100 animationLeftRight tans3s"
              style="flex-grow: 1"
            ></div>
          </div>
          <div
            class="box-root flex-flex"
            style="grid-area: 2 / 15 / auto / end"
          >
            <div
              class="box-root box-background--cyan200 animationRightLeft tans4s"
              style="flex-grow: 1"
            ></div>
          </div>
          <div
            class="box-root flex-flex"
            style="grid-area: 3 / 14 / auto / end"
          >
            <div
              class="box-root box-background--blue animationRightLeft"
              style="flex-grow: 1"
            ></div>
          </div>
          <div
            class="box-root flex-flex"
            style="grid-area: 4 / 17 / auto / 20"
          >
            <div
              class="box-root box-background--gray100 animationRightLeft tans4s"
              style="flex-grow: 1"
            ></div>
          </div>
          <div
            class="box-root flex-flex"
            style="grid-area: 5 / 14 / auto / 17"
          >
            <div
              class="box-root box-divider--light-all-2 animationRightLeft tans3s"
              style="flex-grow: 1"
            ></div>
          </div>
        </div>
      </div>
      <div
        class="box-root padding-top--24 flex-flex flex-direction--column"
        style="flex-grow: 1; z-index: 9"
      >
        <div
          class="box-root padding-top--48 padding-bottom--24 flex-flex flex-justifyContent--center"
        >
        <span
        ><img
          src="../static/img/tg-logo.png"
          alt="logoTamgram"
          width="150px"
          height="150px"

           /></span
    ></a>
          <h1>
            <a

              rel="dofollow"
              style="
                color: #299bf3;
                font-family: 'Poppins', sans-serif;
                font-weight: bold;
              "
              >Tangram Bank

          </h1>
        </div>
        <div class="formbg-outer">
          <div class="formbg">
            <div class="formbg-inner padding-horizontal--48">
              <div> {% include 'message.html' %} </div>
              <span class="padding-bottom--15">Quem poupa ganha😜</span>
              <form id="stripe-login" method="post" action="{{ url_for('auth.login_confirm') }}">
                <div class="field padding-bottom--24">
                  <label for="email">Email</label>
                  <input type="email" name="email" />
                </div>
                <div class="field padding-bottom--24">
                  <div class="grid--50-50">
                    <label for="password">Senha</label>
                    <div class="reset-pass">
                      <a href="{{ url_for('views.reset_senha') }}">Esqueceu sua senha?</a>
                    </div>
                  </div>
                  <input type="password" name="password" />
                </div>
                <div
                  class="field field-checkbox padding-bottom--24 flex-flex align-center"
                >
                  <label for="checkbox">
                    <input class="jamesbond" type="checkbox" name="checkbox" /> Aprenda
                    matemática financeira de uma maneira divertida!!!
                  </label>
                </div>
                <div class="field padding-bottom--24">
                  <input
                    style="background-color: #299bf3"
                    type="submit"
                    name="submit"
                    value="Entrar"
                  />

                </div>
                <div class="field">
                  <a class="ssolink" href="#">Quem Poupa ganha😜</a>
                </div>
              </form>
            </div>
          </div>
          <div class="footer-link padding-top--24">
            <span
              >Não tem uma conta no jogo?
              <a href="{{ url_for('views.cadastro') }}">Cadastre aqui✏️</a></span
            >
            <footer>
              {% include 'footer.html' %}
            </footer>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

scr/templates/nova_senha.html
{% extends "template_dashboard.html" %}
{% block title %} Esqueceu Senha {% endblock %}
{% block conteudo %}
<div>{% include 'message.html' %}</div>
  </br>
  <h1>Informe sua nova senha abaixo:</h1>
  <form role="form" method="POST" action="{{ url_for('auth.nova_senha_post', id=id) }}">
    <div class="mb-3">
      <label for="senha" class="form-label">Nova Senha</label>
      <input type="password" class="form-control" id="senha" name="senha1" placeholder="Sua Senha Nova" required>
      <br>
      <input type="password" class="form-control" id="senha2" name="senha2" placeholder="Repete a senha (verificar)" required>
    </div>
  <button type="submit" class="btn btn-primary">Confirmar</button>
  </form>
{% endblock %}